defaultNamespace: netapp-trident
namespaceAnnotations:
  fleet-managed: "true"

helm:
  releaseName: v24.10.0
  chart: "trident-operator"
  repo: "https://netapp.github.io/trident-helm-chart"
  force: false
  takeOwnership: true
  timeoutSeconds: 0
  values:
    replicas: 2